### ISSUE TITLE
Empty text output

### ISSUE THREAD

**Issue by Palmik** [jrmuizel/pdf-extract#62] opened 2023-07-11 17:59 UTC
Not sure if you are collecting such examples, but here's one:

The PDF: [Model-Card-Claude-2.pdf](https://github.com/jrmuizel/pdf-extract/files/12017696/Model-Card-Claude-2.pdf)
`pdftotext` and `pdf.js` both work on this file.

**Comment by whyayala** [comment] 2023-08-04 14:29
I want to piggy back onto this and say I also had a document that had a full page omitted from the output. Its a [military technical manual](https://www.wbdg.org/FFC/ARMYCOE/COETM/tm_5_601.pdf). 

More can be found [here](https://www.wbdg.org/ffc/army-coe/technical-manuals-tm) though I had only tested against the one I linked above.

**Comment by jrmuizel** [comment] 2023-08-28 15:13
The cause of the problem with [Model-Card-Claude-2.pdf](https://github.com/jrmuizel/pdf-extract/files/12017696/Model-Card-Claude-2.pdf) is an upstream problem in lopdf. I've filed a PR for it here: https://github.com/J-F-Liu/lopdf/pull/245

**Comment by jrmuizel** [comment] 2023-08-29 00:32
> I want to piggy back onto this and say I also had a document that had a full page omitted from the output. Its a [military technical manual](https://www.wbdg.org/FFC/ARMYCOE/COETM/tm_5_601.pdf).

@whyayala which page was omitted?

**Comment by leumasme** [comment] 2024-01-28 15:26
Upstream PR was already merged and released but the issue persists in pdf-extract 0.7.4, I believe because cargo.toml depends on lopdf "0.30.0" which won't match "0.32.0".  
Can deps be bumped to fix this?

**Comment by leumasme** [comment] 2024-02-02 09:58
Can confirm that bumping lopdf to 0.32.0 fixes text output for the pdf linked in this issue. Some different samples are still outputting an empty string, so there seem to be more issues that cause this symptom.

**Comment by jrmuizel** [comment] 2024-12-28 19:20
This is fixed now.

**Closed by jrmuizel** 2024-12-28 19:20 UTC
